# Change prefix to C-a
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Start with bash as default shell
set -g default-command "bash"

# Enable 256 terminal color support
set-option -sa terminal-overrides ",xterm*:Tc"

# Set escape time to zero
set -s escape-time 0

# Status bar style
set -g status-style 'bg=#333333 fg=#5eacd3'
set -g base-index 1

set -g mouse on # Enable mouse
set -g renumber-windows on # Renumber windows when closed
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection

# vim-like pane switching
# bind -r ^ last-window
# bind -r k select-pane -U
# bind -r j select-pane -D
# bind -r h select-pane -L
# bind -r l select-pane -R

# Same, but do not repeat
bind ^ last-window
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# vim-like splits
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf

# Swap windows
bind N swap-window -d -t +1
bind P swap-window -d -t -1

# Custom binds
bind o popup -E "alacritty-opacity"
bind O popup -E "alacritty-scheme2 --fzf"

# Copy current command
bind Z run "bash -c '
    tmux send-keys 'C-a'
    tmux copy-mode
    tmux send-keys 'v' '$' 'h'
    tmux send-keys Enter
'"
