#!/usr/bin/env bash

selected=$(fzf --cycle << EOF
 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
100%
EOF
)

if [ -n "$selected" ]; then
    opacity=$(bc -l <<< "${selected%\%*} / 100")
    echo OPacity: $opacity
    alacritty msg config -w -1 "window.opacity=$(printf '%.2f' $opacity)"
fi
