#!/usr/bin/env bash

if [ -n "$1" ]; then
    selected=$1
else
    selected=$(fzf --cycle << EOF
100%
90%
80%
70%
60%
50%
40%
30%
20%
10%
0%
EOF
    )
fi

if [ -n "$selected" ]; then
    opacity="${selected%\%}"
    opacity=$([ "$opacity" == "100" ] && echo "1" || echo "0.$opacity")
    alacritty msg config -w -1 "window.opacity=$opacity"
fi
