#!/usr/bin/env bash

start_season=1
start_episode=1
show_help=false
show_path=""
show_name=""
strip_part=true

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            show_help=true
            shift
            ;;
        -no-strip)
            strip_part=false
            shift
            ;;
        -s)
            shift
            start_season="$1"
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            show_path="$1"
            shift
            show_name="$1"
            shift
            ;;
    esac
done

# echo start_season $start_season
# echo start_episode $start_episode
# echo show_help $show_help
# echo show_path $show_path
# echo show_name $show_name

# if [ show_help ]; then
#     echo "TODO: This is a help message"
#     exit 0;
# fi

if [ -z "$show_path" ]; then
    echo "Show path is required"
    exit 1;
fi

if [ -z "$show_name" ]; then
    echo "Show name is required"
    exit 1;
fi

count=$start_episode;
while read -r line; do
    if [ strip_part ]; then
        source_path="$(basename "$line" .part)"
    else
        source_path="$line"
    fi

    file_extension="${source_path##*.}"
    season="$(printf '%02d' "$start_season")"
    episode="$(printf '%02d' "$count")"
    destination_path="$(realpath "${show_path}/${show_name}_S${start_season}E${episode}.${file_extension}")"

    echo ln -sr \""$source_path"\" \""$destination_path"\"

    count=$((count + 1))
done
