#!/usr/bin/env bash

wallpaper_folder="$HOME/fs/imagenes/fondos"

if [[ $1 == "--random" || $1 == "-r" ]]; then
    selected=$(find "$wallpaper_folder" ~/fs/imagenes/fondos/ -type f | shuf -n 1)
else
    selected=$(find "$wallpaper_folder" ~/fs/imagenes/fondos/ -type f | fzf --cycle --delimiter / --with-nth -1)
fi

if [ -n "$selected" ]; then
    case "$XDG_CURRENT_DESKTOP" in
        "hyprland")
            hyprctl hyprpaper reload ,"$selected" &> /dev/null
            ;;
        "GNOME")
            gsettings set org.gnome.desktop.background picture-uri "file://$selected"
            gsettings set org.gnome.desktop.background picture-uri-dark "file://$selected"
            ;;
        *)
            echo "Desktop session not recognised"
            exit 1
            ;;
    esac
fi
