#!/usr/bin/env bash

desktop=$DESKTOP_SESSION
wallpaper_folder="$HOME/fs/imagenes/fondos"

selected=$(find $wallpaper_folder -type f -printf '%f\n' | fzf --cycle)

if [ -n "$selected" ]; then
    case "$XDG_CURRENT_DESKTOP" in
        "hyprland")
	    hyprctl hyprpaper reload ,"$wallpaper_folder/$selected" &> /dev/null
            ;;
        "GNOME")
            gsettings set org.gnome.desktop.background picture-uri-dark "file://$wallpaper_folder/$selected"
            gsettings set org.gnome.desktop.background picture-uri "file://$wallpaper_folder/$selected"
            ;;
        *)
            echo "Desktop session not recognised"
            ;;
    esac
fi
