set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf
set -g base-index 1

setw -g mode-keys vi
set -g mouse on # Enable mouse
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
# bind -r ^ last-window
# bind -r k select-pane -U
# bind -r j select-pane -D
# bind -r h select-pane -L
# bind -r l select-pane -R

# Same, but do not repeat
bind ^ last-window
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# vim-like splits
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Custom binds
bind Z run 'bash ~/.config/tmux/copy-cmd.bash'
bind o run "alacritty msg config -t -1 'window.opacity=0.85'"
bind O run "alacritty msg config -t -1 'window.opacity=1'"

# Pack windows automatically
set-option -g renumber-windows on

# Swap windows
bind N swap-window -d -t +1
bind P swap-window -d -t -1
